### ISSUE TITLE
Error when using latest version of pip

### ISSUE THREAD

**Issue by yizhang-zen** [poise/poise-python#107]
See https://github.com/poise/poise-python/blob/master/lib/poise_python/resources/python_package.rb#L41

I ran into error, since pip has new releases recently

```
STDERR: The python_package resource requires pip >= 6.1.0, currently 10.0.0b2
```

it should check something like `^[0-6]\\.0` so it does not match `10`

**Comment by collinpeters** [comment]
This is breaking our build as well. Any way to work around this?

**Comment by yizhang-zen** [comment]
I added python_runtime block with a pip version in the our recipe, as a temp fix. It works for me: `python_runtime '2.7' do
  pip_version '9.0.3'
end`

**Comment by yizhang-zen** [comment]
@coderanger Could you have a look please? :)

**Comment by yizhang-zen** [comment]
sorry..same here...add the block I mentioned before didn't work. :/

**Comment by chris-redekop** [comment]
I encountered this error and worked around it by adding the indicated `pip_version` line to my recipe.

```
case node['platform_family']
when 'amazon'
  package_name = 'python36'
else
  package_name = 'python3'
end

python_runtime '3' do
  provider :system

  # See https://github.com/poise/poise-python/issues/107
  pip_version '9.0.3'

  options :system, package_name: package_name
end
```

**Comment by barracksbuilder** [comment]
Any word on this getting fixed and merged into master. This breaks the AWS code deploy agent which takes down our entire environment. We use berks to manage dependencies and I haven't found a way to overwrite the pip version from an attributes wrapper.

**Comment by bcg62** [comment]
also running into this issue

**Comment by yonilevy** [comment]
same issue here. this regex is super weird, what is it even supposed to do? also, you don't need to escape that backslash there, you're using a raw string literal...

**Comment by coderanger** [comment]
Literally everyone is running into this issue, please stop with the me toos. It takes a few days to test with new major releases and whatnot, for now you’ll need to pin back to pip 9 to use this cookbook.

**Comment by barracksbuilder** [comment]
@coderanger,
Is there a way to pin pip 9 through an attribute? 
I see override['poise-python']['options']['pip_version'] = false can I use my wrapper to pin from there?

**Comment by coderanger** [comment]
Yes, you can set any provider option via that system.

**Comment by et304383** [comment]
Serious question, what on earth was that regex trying to match?

**Comment by andy-v-h** [comment]
To get around this issue I had to specify a different pip_url

**Comment by davidmontgom** [comment]
this is a major issue.  I had a server die and I had to rector 10 cookbooks to install via bash.  Is this cookbook no longer maintained?

**Comment by coderanger** [comment]
@davidmontgom I already responded to you once. Stop it.

**Comment by raghav8888** [comment]
@coderanger Needed a bit of guidance since I'm pretty new to chef. Went through the concept of wrapper cookbooks. From the [comment](https://github.com/poise/poise-python/issues/107#issuecomment-381770648), all I need to do is:
1. Include dependency in metadata.rb
2. In my cookbook's default.rb, `include_recipe 'poise-python::default'`
3. Include the line below line in my cookbook's attribute file
`default['poise-python']['options']['get_pip_url'] = 'https://raw.githubusercontent.com/pypa/get-pip/master/2.6/get-pip.py'``

Could you confirm?

**Comment by raghav8888** [comment]
oh cool. Thanks. Will implement that till this gets fixed.

**Comment by eyalzek** [comment]
@coderanger thanks for the info, might I suggest to make the documentation for the `pip_version` attribute a bit more clear?

```
pip_version – Version of pip to install. If set to true, use the latest. If set to false, do not install pip. For backward compatibility, can also be set to a URL instead of get_pip_url. (default: true)
```

It makes sense that it takes a version string since it says: `Version of pip to install`, but I find the second sentence to be a bit misleading in that it makes me think that this attribute should be a boolean.

**Comment by et304383** [comment]
I'm having a little trouble understanding the lack of sense of urgency here.  Many (all) people are affected by this who updated to pip 10.  Yet, it's been over two weeks and no fix is in place nor has the PR which could resolve this been merged.

I get that everyone is busy and what not, but @coderanger you've replied several times to this thread indicating you have at least some availability.  I understand wanting to test and what not, but at this point what are you worried about?  Making the cookbook more broken?  This is hotfix territory.  Push out a fix that hopefully works and worry about thoroughly testing and/or refining it later.

**Comment by barracksbuilder** [comment]
@et304383,
There is urgency here but @coderanger is only one person. The version check isn't the only issue with PIP 10 they changed some of the API calls. You can pin PIP to 9.0.3 to get it running again. If you use a wrapper like I do because I'm really only using this cookbook for the aws-codedeploy-agent you can use the override attribute stated above. If you are actually using the cookbook each item has the ability to set the PIP version so pin it there.

**Comment by gsdevme** [comment]
@barracksbuilder @et304383 Open source software! 

Im attempting to use the attribute work around on CentOS 6.9 though and running into

```

**Comment by paustin01** [comment]
For others here I came across this issue via the cloudcli chef cookbook which depends on this cookbook (both at latest versions). Adding the following to the attributes file of my wrapper cookbook did the trick.

```ruby
override['poise-python']['options']['pip_version'] = '9.0.3'
```

**Comment by jeffbyrnes** [comment]
In case anyone is using the `get-pip.py` from pypa.io, here’s how I dealt with that:

```ruby
remote_file file_cache_path('get-pip.py') do
  source 'https://bootstrap.pypa.io/get-pip.py'
  notifies :run, "python_execute[#{file_cache_path('get-pip.py')} 'pip<10']", :immediately
end

python_execute "#{file_cache_path('get-pip.py')} 'pip<10'" do
  action :nothing
end
```

**Comment by scalp42** [comment]
@jeffbyrnes I'm confused in what order do you run this?

I also tried to set `pip_version` to false in the python_runtime resource but no dice.

`python_execute` requires a runtime, so not sure how you managed to run it? Or maybe you have a system python package installed before?

**Comment by coderanger** [comment]
Poise-python 1.7.0 is up with full support for both Pip 10 and Chef 14.
