### ISSUE TITLE
python_package should support all of pip's flags

### ISSUE THREAD

**Issue by mattdeboard** [poise/poise-python#27]
pip's `--editable` flag, especially, would be useful, but even more "esoteric" ones like `--process-dependency-links` would be good as well. 

The quickest impl I can think of would be like a `pip_flags ["--editable", "--process-dependency-links"]`, but I guess you could make each one a proper attribute.

**Comment by mattdeboard** [comment]
Oh, wait: This is provided as part of Chef's `package` resource. Disregard!

**Comment by coderanger** [comment]
The problem is that I used (effectively) `pip list` to check which versions of each package are currently and installed and which versions are available on PyPI. Some flags need to be given to list too to make it work (eg. `--index-url`) but others would be an error, like `--editable`. It will require a lot more funky stuff to make it work. That said, it should support at least some of them.

**Comment by mattdeboard** [comment]
I see, that makes sense. However it appears just using `package`'s `options` clause seems to do the trick, though it's possible I'm missing something.

@coderanger Does `python_package` support installing a package from a VCS repo? I couldn't find a way yesterday so I just punted and used `execute` to invoke pip direct.

**Comment by coderanger** [comment]
No, it does not. As it is based on the core package resource, it needs to work in a similar way. If you installing things non-idempotently should use the `pip_requirements` resource most likely.

**Comment by mattdeboard** [comment]
Alright, thanks!
