### ISSUE TITLE
Python.h file is missing from /usr/include/python2.7

### ISSUE THREAD

**Issue by lioramilbaum** [poise/poise-python#66]
Should /usr/include/python2.7 end up as sym link to: 
/opt/rh/python27/root/usr/include/python2.7

**Comment by coderanger** [comment]
No, the SCL packages are designed to be entirely independent from the "normal" system. When you run stuff via the resources in this cookbook, it should fix up all the various environment variables for you. If running outside of Chef, you may need to use the `scl` helper tool. You can also switch to using the `:system` provider, which will give you fewer options in terms of versions but less wonky packaging stuffs.

**Comment by lioramilbaum** [comment]
I am not sure I understood your comment, but, my custom cookbook requires python to be installed on the system and depends on python include files. The default location is /usr/include/python2.7.
How should I fix my custom cookbook to find the include files?

**Comment by coderanger** [comment]
By default on RHEL and CentOS, `python_runtime` installs Python using the SoftwareCollections.org packages. These have newer versions of Python, which is why they are preferred, but they have some oddities about how things are compiled. SCL packages are designed to exist in parallel with the standard OS packages, as well as in parallel with each other. Whatever you are installing either you need to fix it to understand the different paths, or don't use the SCL packages. The cookbook README shows how to use different providers.

**Comment by lioramilbaum** [comment]
My system is RHEL. I am installing the Development Tools with yum (yum -y groupinstall "Development Tools")
I am including poise_python::default recipe in my custom recipe

The software I am installing runs gcc ... -I/usr/include/python2.7.....
The gcc command fails becuase it can't find Python.h include file.

What is the best way to fix it?

**Comment by coderanger** [comment]
The simplest way is to set the attribute `override['poise-python']['provider'] = 'system'` in your cookbook's attributes file (or set the same value in a role or whatever else). That will force it to use the system packages which have the files you expect. Just remember that if you're on RHEL6 that means you're going to get 2.6, not 2.7.

**Comment by lioramilbaum** [comment]
Worked. Thanks.
