### ISSUE TITLE
python_runtime '2.7' - Installation Error

### ISSUE THREAD

**Issue by lioramilbaum** [poise/poise-python#68]
Package python would install 2.6.6-66.el6_8, which does not match 2.7. Please set the package_name or package_version provider options.

**Comment by coderanger** [comment]
You requested Python 2.7 using the `:system` provider but the system package available if Python 2.6, so it's raising an error to tell you either change the requested version or the provider, or something else in the configuration (package_name, etc).

**Comment by grizo** [comment]
@lioramilbaum not sure if you resolved this but encountered it with cloudcli cookbook and chef-client v14 as it utilizes python_runtime. on rhel6, its broken due to python package being `python-2.6.6-66.el6_8.x86_64` instead of `python2-x`:
```
ERROR: Package python would install 0:2.6.6-66.el6_8.x86_64, which does not match 2. Please set the package_name or package_version provider options.
```
 to resolve this, i set the following override in our cookbook wrapper:
```
if node['platform_version'].to_i == 6 && node['chef_packages']['chef']['version'].to_i >= 14
  default['cloudcli']['aws']['python']['version'] = 0
end
```

no such issue in chef-client v12 or v13.

**Comment by coderanger** [comment]
@grizo The internals of the RPM handling system was entirely re-written for Chef 14 and I haven't yet updated some of this code to match.

**Comment by lioramilbaum** [comment]
I have already resolved this issue. Thanks.
