### ISSUE TITLE
poise-python can't install packages with underscore in name?

### ISSUE THREAD

**Issue by halfinhalfout** [poise/poise-python#71]
For example, 
`pip install cx_Oracle` & `pip install cx-Oracle` _both_ work in the shell.

Here's that python module: https://pypi.python.org/pypi/cx_Oracle

Note, according to http://pybuilder.github.io/documentation/external_plugins.html#.V8cNapMrLUI:

> Pip replaces underscores with dashes

But, 
```
python_package 'cx_Oracle'
```
in a cookbook recipe fails with error:
` Chef::Exceptions::Package: No candidate version available for cx_Oracle`

The following succeeds (with dash instead of underscore):
```
python_package 'cx-Oracle'
```

Is adding support for underscores in package names is difficult, perhaps just adding a note in README would be sufficient to help people avoid this problem.

I can do a PR for the README if you'd like me to.

Thanks!

Doug

**Comment by stevenhair** [comment]
If you're using a private repository like artifactory, it could actually be a problem with that instead of this cookbook. In pip 8, support for fuzzy matching on package names was removed, so the package name needs to match the name in the registry exactly.

**Comment by coderanger** [comment]
No, it's inside my package code. Fix is in progress :)

**Comment by halfinhalfout** [comment]
Much appreciated, @coderanger!

**Comment by mattdodge** [comment]
This fix makes it difficult (if not impossible) to install local wheel files that contain underscores. For example, if I build a local packaged wheel file with package name `my_package` then the resulting wheel filename will be `my_package-1.0.0-py3-none-any.whl`. Just doing a blind string replace makes it impossible to install that. You see errors like this:
```
Requirement 'my-package-1.0.0-py3-none-any.whl' looks like a filename, but the file does not exist
```
I don't feel like it makes sense to just do this underscore replacement because of a, now deprecated, "feature" of pip.
