### ISSUE TITLE
*_version params are bools instead of versions

### ISSUE THREAD

**Issue by tescalada** [poise/poise-python#76]
It doesn't seem like you can use the pip_version, setuptools_version, virtualenv_version, or wheel_version params to actually specify what version of these items to install. The descriptions describe them as "Version of pip to install", but it really means install latest or dont install at all. 

On systems behind very slow connections with metered data, it is a problem always upgrading to the latest version of virtualenv when it is not needed and slows down the chef run considerably. 

This should probably be updated to accept a pinned version of these tools with "True" or "latest" still working as expected for backwards compatibility. 

Unless maybe I am doing something wrong, which is possible. Is there another way I should be configuring this to install virtualenv, but not upgrade it to latest every time?

If there is, then maybe this issue is more about the documentation needing to be clarified around these fields.

**Comment by coderanger** [comment]
The behavior of "install the latest at whatever moment I do the install and then never upgrade it" leads to really fragile systems because if you spin up a new VM, it can end up with totally different state from the previous ones. If you're okay with being version locked, just grab whatever the versions of each tool is today and put them in your node attributes or other options config source. That will ensure that future machines use those versions and you can do upgrades in a controlled manner.

**Comment by tescalada** [comment]
I agree about installing the latest being a very bad practice, my question is about how to make it not do that. The documentation and parameter names are deceiving. Where in the node attributes would I put the version of virtualenv that I would like to be installed? I looked though the source but could not find a place where that version would be taken into account when installing.

**Comment by coderanger** [comment]
For virtualenv in particular it's https://github.com/poise/poise-python/blob/master/lib/poise_python/python_providers/base.rb#L134 but there is similar code for each.

**Comment by tescalada** [comment]
I'm not sure what code I was looking at that make it look like it was only treating this as a bool. This looks like it works as expected. I'll close the issue.
