### ISSUE TITLE
Software Collections URLs broken (again)

### ISSUE THREAD

**Issue by cjflory** [poise/poise-python#78]
It appears the Software Collections URLs are not working again.  This is a pretty major concern for us, as we're attempting to use this cookbook in a production system.  Are there any recommendations for a more stable approach?  It seems the Software Collections URLs have broken at least a few times...  The URL we're attempting to hit is:  https://www.softwarecollections.org/en/scls/rhscl/python27/epel-6-x86_64/download/rhscl-python27-epel-6-x86_64.noarch.rpm

**Comment by coderanger** [comment]
With the most recent rewrite this shouldnt be a problem as we now use the integrated repo package support in CentOS. What version of this and poise-languages are you using?



On November 22, 2016 at 1:07:35 PM EST, Clem Flory <notifications@github.com> wrote:It appears the Software Collections URLs are not working again. This is a pretty major concern for us, as we're attempting to use this cookbook in a production system. Are there any recommendations for a more stable approach? It seems the Software Collections URLs have broken at least a few times... The URL we're attempting to hit is: https://www.softwarecollections.org/en/scls/rhscl/python27/epel-6-x86_64/download/rhscl-python27-epel-6-x86_64.noarch.rpm  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.           {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/poise/poise-python","title":"poise/poise-python","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/poise/poise-python"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Software Collections URLs broken (again) (#78)"}],"action":{"name":"View Issue","url":"https://github.com/poise/poise-python/issues/78"}}}

**Comment by cjflory** [comment]
We're using poise-python v1.4.0, and poise-languages ~> 2.0 (so I believe it's using v2.0.3).  Are you saying upgrading to poise-python v1.5.1 should fix this issue?

**Comment by cjflory** [comment]
My mistake, it looks like we are using poise-languages v1.4.0.

**Comment by coderanger** [comment]
Yep, this was specifically what 1.5 fixed.

**Comment by keen99** [comment]
jumping from 1.4.0 to 1.5.1 fixed it for me, thanks.  wish there was a good way to know about these changes, I hunted around in issues and PRs but failed to identify where this might have been fixed... (probably should have opened an issue this AM, but Meetings Happen....)

**Comment by cjflory** [comment]
Thanks for the help!  I wasn't able to get the `scl` provider to work for me, using v1.5.1 (I think because of a subscription issue), so I am building/installing Python from source, and using the `dummy` provider.

One thing I did notice though, is [this code](https://github.com/poise/poise-languages/blob/master/lib/poise_languages/scl/resource.rb#L106-L112) in poise-languages.  According to the [Software Collections documentation](https://www.softwarecollections.org/en/scls/rhscl/python27/), I'm not sure poise-languages is using the correct command.  It's currently using `subscription-manager`, and the [Software Collections documentation](https://www.softwarecollections.org/en/scls/rhscl/python27/) for RHEL say to use the following:

    yum-config-manager --enable rhel-server-rhscl-6-rpms  # RHEL 6
    yum-config-manager --enable rhel-server-rhscl-7-rpms  # RHEL 7

**Comment by coderanger** [comment]
@cjflory Are you using RHEL on one of the cloud provider images or a "real" install? `subscription-manager` is a newer replacement for `yum-config-manager`.

**Comment by cjflory** [comment]
I'm using a "real" install.  For testing, we have `.box` files pre-created for Vagrant/Virtualbox, and our sandbox and production environments are "real" installs.  I believe the `scl` provider would have worked in our sandbox and production environments, but I needed our cookbook to work for testing also, which is why I chose to build from source.

**Comment by coderanger** [comment]
@cjflory You should contact your RedHat sales rep then, as RHSCL should be included with all RHEL subscriptions.

**Comment by coderanger** [comment]
(unless you don't have your subscription info set up correctly)

**Comment by cjflory** [comment]
Well, another reason we decided to build from source, was to reduce the number of external dependencies (we already do this with `pip` packages, for example).
