### ISSUE TITLE
 Error executing action `install` on resource 'rpm_package[rhscl-python27]'

### ISSUE THREAD

**Issue by JGONGSQ** [poise/poise-python#79]
Error executing action `install` on resource 'rpm_package[rhscl-python27]'

Here is the error message, I think the rpm package has been removed from software collection, can you do a very quick update on the source link?

23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         ================================================================================
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         Mixlib::ShellOut::ShellCommandFailed
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         ------------------------------------
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         Expected process to exit with [0], but received '1'
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         ---- Begin output of rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         ' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-7-x86_64/download/rhscl-python27-epel-7-x86_64.noarch.rpm ----
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         STDOUT: 
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         STDERR: curl: (22) The requested URL returned error: 404 NOT FOUND
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         error: open of https://www.softwarecollections.org/en/scls/rhscl/python27/epel-7-x86_64/download/rhscl-python27-epel-7-x86_64.noarch.rpm failed: No such file or directory
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         ---- End output of rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         ' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-7-x86_64/download/rhscl-python27-epel-7-x86_64.noarch.rpm ----
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         Ran rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         ' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-7-x86_64/download/rhscl-python27-epel-7-x86_64.noarch.rpm returned 1
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         
23-Nov-2016 08:59:13	ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com         Cookbook Trace:

Kind regards,
James

**Comment by JGONGSQ** [comment]
No longer an issue with 1.5.1

**Comment by coderanger** [comment]
Please upgrade to at least version 1.5 of the cookbook.



On November 22, 2016 at 6:09:24 PM EST, JGONGSQ <notifications@github.com> wrote:Error executing action install  on resource 'rpm_package[rhscl-python27]'  Here is the error message, I think the rpm package has been removed from software collection, can you do a very quick update on the source link?  23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com ================================================================================ 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com Mixlib::ShellOut::ShellCommandFailed 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com ------------------------------------ 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com Expected process to exit with [0], but received '1' 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com ---- Begin output of rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE} 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com ' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-7-x86_64/download/rhscl-python27-epel-7-x86_64.noarch.rpm ---- 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com STDOUT: 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com STDERR: curl: (22) The requested URL returned error: 404 NOT FOUND 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com error: open of https://www.softwarecollections.org/en/scls/rhscl/python27/epel-7-x86_64/download/rhscl-python27-epel-7-x86_64.noarch.rpm failed: No such file or directory 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com ---- End output of rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE} 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com ' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-7-x86_64/download/rhscl-python27-epel-7-x86_64.noarch.rpm ---- 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com Ran rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE} 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com ' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-7-x86_64/download/rhscl-python27-epel-7-x86_64.noarch.rpm returned 1 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com 23-Nov-2016 08:59:13 ec2-13-54-117-66.ap-southeast-2.compute.amazonaws.com Cookbook Trace:  Kind regards, James  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.           {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/poise/poise-python","title":"poise/poise-python","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/poise/poise-python"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":" Error executing action `install` on resource 'rpm_package[rhscl-python27]' (#79)"}],"action":{"name":"View Issue","url":"https://github.com/poise/poise-python/issues/79"}}}
